### ISSUE TITLE
todo : 블로그, 사이트 상호 링크 추가

### ISSUE THREAD

**Issue by jsg3121** [jsg3121/pokemon#55]
- [x] 사이트 -> 블로그 링크 추가
- [x] 블로그 -> 사이트 링크 추가
- [x] 사이트 - github 링크 추가
